---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: ".vuepress/theme.json"
  label: Theme Settings
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: works
  label: Works
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: journal
  label: Journal
  create: all
  match: "**/[!index]*.md"
  templates:
  - journal
upload_dir: ".vuepress/public/upload"
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
