---
new_page_extension: md
auto_deploy: true
admin_path: "/adminfff"
webhook_url: 
sections:
- type: directory
  path: ''
  label: dur
  create: all
  match: "**/*"
- type: directory
  path: ".vuepress/toml"
  label: TOML
  create: all
  match: "**/*"
  new_doc_ext: toml
- type: directory
  path: ".vuepress/yaml"
  label: YAML
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: document
  path: ".vuepress/theme.json"
  label: Theme Settings
- type: directory
  path: ".vuepress/data"
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: json
- type: heading
  label: Content
- type: directory
  path: works
  label: Works
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: journal
  label: Journal
  create: all
  match: "**/[!index]*.md"
  templates:
  - journal
upload_dir: ".vuepress/public/upload"
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
